export default
    {
        landingpage: {
            en: "As communication continues to increase on a global scale, so too does the demand for quick, reliable translation. With AllChat, you can talk to anyone across the world, even if you don't speak their language.",
            es: "A medida que la comunicación continúa aumentando a escala global, también lo hace la demanda de una traducción rápida y confiable. Con AllChat, puede hablar con cualquier persona en todo el mundo, ¡incluso si no habla su idioma.",
            zh: "随着通信在全球范围内的持续增长，对快速，可靠翻译的需求也越来越大。使用AllChat，即使您不说他们的语言，也可以与世界各地的任何人交谈.",
            ar: "مع استمرار زيادة الاتصالات على نطاق عالمي ، يزداد أيضًا الطلب على الترجمة السريعة والموثوقة. مع AllChat ، يمكنك التحدث إلى أي شخص في جميع أنحاء العالم ، حتى لو كنت لا تتحدث لغتهم.",
            fr: "Comme la communication continue d'augmenter à l'échelle mondiale, il en va de même pour la demande de traduction rapide et fiable. Avec AllChat, vous pouvez parler à n'importe qui à travers le monde, même si vous ne parlez pas leur langue.",
            de: "Da die Kommunikation weltweit weiter zunimmt, steigt auch die Nachfrage nach schnellen und zuverlässigen Übersetzungen. Mit AllChat können Sie mit jedem auf der ganzen Welt sprechen, auch wenn Sie seine Sprache nicht sprechen.",
            hi: "चूंकि वैश्विक स्तर पर संचार में वृद्धि जारी है, इसलिए त्वरित, विश्वसनीय अनुवाद की मांग भी है। ऑलचैट के साथ, आप दुनिया भर में किसी से भी बात कर सकते हैं, भले ही आप उनकी भाषा न बोलते हों.",
            ja: "コミュニケーションが世界規模で増加し続けるにつれて、迅速で信頼性の高い翻訳に対する要求も高まっています。 AllChatを使用すると、たとえ彼らの言語を話さなくても、世界中の誰とでも話すことができます",
            ko: "통신이 전 세계적으로 계속 증가함에 따라 빠르고 안정적인 번역에 대한 요구도 증가합니다. AllChat을 사용하면 언어를 구사하지 않아도 전 세계의 모든 사람과 대화 할 수 있습니다.",
            ru: "По мере того как общение продолжает расти в глобальном масштабе, растет и потребность в быстром и надежном переводе. С AllChat вы можете общаться с кем угодно по всему миру, даже если вы не говорите на его языке.",
            tl: "Tulad ng patuloy na pagtaas ng komunikasyon sa isang global scale, gayon din ang hinihingi para sa mabilis, maaasahang pagsasalin. Sa AllChat, maaari kang makipag-usap sa kahit sino sa buong mundo, kahit na hindi ka nagsasalita ng kanilang wika.",
            te: "ప్రపంచ స్థాయిలో కమ్యూనికేషన్ పెరుగుతూనే ఉన్నందున, శీఘ్ర, నమ్మకమైన అనువాదం కోసం డిమాండ్ కూడా పెరుగుతుంది. AllChat తో, మీరు వారి భాష మాట్లాడకపోయినా ప్రపంచవ్యాప్తంగా ఎవరితోనైనా మాట్లాడవచ్చు.",
            vi: "Khi truyền thông tiếp tục tăng trên phạm vi toàn cầu, thì nhu cầu dịch thuật nhanh chóng, đáng tin cậy cũng vậy. Với AllChat, bạn có thể nói chuyện với bất kỳ ai trên toàn thế giới, ngay cả khi bạn không nói được ngôn ngữ của họ."
        },
        welcome: {
            en: "Welcome to AllChat!",
            es: "¡Bienvenido a AllChat!",
            zh: "欢迎来到AllChat！",
            ar: "مرحبًا بك في AllChat!",
            fr: "Bienvenue sur AllChat!",
            de: "Willkommen bei AllChat!",
            hi: "AllChat में आपका स्वागत है!",
            ja: "AllChatへようこそ！",
            ko: "AllChat에 오신 것을 환영합니다!",
            ru: "Добро пожаловать в AllChat!",
            tl: "Maligayang pagdating sa AllChat!",
            te: "ఆల్ చాట్‌కు స్వాగతం!",
            vi: "Chào mừng đến với AllChat!"
        },
        bring: {
            en: "Bring People Together",
            es: "Juntar a la gente",
            zh: "凝聚人心",
            ar: "جمع الناس معا",
            fr: "Rassembler les gens",
            de: "Leute zusammenbringen",
            hi: "लोगों को एक साथ लाने के लिए",
            ja: "人をつなぐ",
            ko: "사람들을 하나로 모으기",
            ru: "Соберите людей вместе",
            tl: "Magkasama ang mga Tao",
            te: "ప్రజలను కలిసి తీసుకురండి",
            vi: "Đưa mọi người gần lại với nhau"
        },
        start: {
            en: "Start Chatting",
            es: "Comience a chatear",
            zh: "开始聊",
            ar: "ابدأ الدردشة",
            fr: "Commencez à discuter",
            de: "Starten Sie den Chat",
            hi: "चैटिंग शुरू करें",
            ja: "チャットを開始",
            ko: "채팅 시작",
            ru: "Начать чат",
            tl: "Mag-umpisang mag-usap",
            te: "చాటింగ్ ప్రారంభించండి",
            vi: "Bắt đầu trò chuyện"
        },
        rooms: {
            en: "Chatrooms",
            es: "Habitaciones",
            zh: "房间数",
            ar: "غرف",
            fr: "Pièces",
            de: "Räume",
            hi: "कमरा",
            ja: "部屋",
            ko: "대화방",
            ru: "Чаты",
            tl: "Mga silid",
            te: "రూములు",
            vi: "Phòng"
        },
        signout: {
            en: "Sign Out",
            es: "Desconectar",
            zh: "登出",
            ar: "خروج",
            fr: "Déconnexion",
            de: "Ausloggen",
            hi: "प्रस्थान करें",
            ja: "サインアウト",
            ko: "로그 아웃",
            ru: "Выход",
            tl: "Mag-sign Out",
            te: "సైన్ అవుట్ చేయండి",
            vi: "Đăng xuất"
        },
        logged: {
            en: "Logged In",
            es: "Conectado",
            zh: "登录",
            ar: "تم تسجيل الدخول",
            fr: "Connecté",
            de: "Eingeloggt",
            hi: "पमें लॉग इन",
            ja: "ログインしました",
            ko: "로그인",
            ru: "Войти в систему",
            tl: "Nakalog-in",
            te: "లాగిన్ అయ్యారు",
            vi: "Đăng nhập"
        },
        norooms: {
            en: "No Rooms, Create One and Get Started!",
            es: "¡Sin habitaciones, cree una y comience!",
            zh: "没有房间，创建一个并开始！",
            ar: "لا غرف ، أنشئ غرفة وابدأ!",
            fr: "Pas de chambres, créez-en une et commencez!",
            de: "Keine Zimmer, erstellen Sie eines und legen Sie los!",
            hi: "नो रूम, क्रिएट वन एंड गेट स्टार्टेड!",
            ja: "部屋なし、1つ作成して始めましょう！",
            ko: "방 없음, 하나 만들기 및 시작!",
            ru: "Нет комнат, создайте и начните!",
            tl: "Walang mga Kuwarto, Lumikha ng Isa at Magsimula!",
            te: "గదులు లేవు, ఒకదాన్ని సృష్టించండి మరియు ప్రారంభించండి!",
            vi: "Không có phòng, tạo một và bắt đầu!"
        },
        demo: {
            en: "How AllChat Works",
            es: "Cómo funciona AllChat",
            zh: "AllChat如何运作",
            ar: "كيف يعمل AllChat",
            fr: "Comment fonctionne AllChat",
            de: "Wie AllChat funktioniert",
            hi: "ऑलचैट कैसे काम करता है",
            ja: "AllChatの仕組み",
            ko: "AllChat 작동 방식",
            ru: "Как работает AllChat",
            tl: "Paano gumagana ang AllChat",
            te: "ఆల్ చాట్ ఎలా పనిచేస్తుంది",
            vi: "Cách thức hoạt động của AllChat"
        },
    }