export default
    {
        landingpage: {
            en: "As communication continues to increase on a global scale, so too does the demand for quick, reliable translation. With AllChat, you can talk to anyone across the world, even if you don't speak their language.",
            es: "A medida que la comunicación continúa aumentando a escala global, también lo hace la demanda de una traducción rápida y confiable. Con AllChat, puede hablar con cualquier persona en todo el mundo, ¡incluso si no habla su idioma.",
            zh: "随着通信在全球范围内的持续增长，对快速，可靠翻译的需求也越来越大。使用AllChat，即使您不说他们的语言，也可以与世界各地的任何人交谈.",
            ar: "مع استمرار زيادة الاتصالات على نطاق عالمي ، يزداد أيضًا الطلب على الترجمة السريعة والموثوقة. مع AllChat ، يمكنك التحدث إلى أي شخص في جميع أنحاء العالم ، حتى لو كنت لا تتحدث لغتهم.",
            fr: "Comme la communication continue d'augmenter à l'échelle mondiale, il en va de même pour la demande de traduction rapide et fiable. Avec AllChat, vous pouvez parler à n'importe qui à travers le monde, même si vous ne parlez pas leur langue.",
            de: "Da die Kommunikation weltweit weiter zunimmt, steigt auch die Nachfrage nach schnellen und zuverlässigen Übersetzungen. Mit AllChat können Sie mit jedem auf der ganzen Welt sprechen, auch wenn Sie seine Sprache nicht sprechen.",
            hi: "चूंकि वैश्विक स्तर पर संचार में वृद्धि जारी है, इसलिए त्वरित, विश्वसनीय अनुवाद की मांग भी है। ऑलचैट के साथ, आप दुनिया भर में किसी से भी बात कर सकते हैं, भले ही आप उनकी भाषा न बोलते हों.",
            ja: "コミュニケーションが世界規模で増加し続けるにつれて、迅速で信頼性の高い翻訳に対する要求も高まっています。 AllChatを使用すると、たとえ彼らの言語を話さなくても、世界中の誰とでも話すことができます",
            ko: "통신이 전 세계적으로 계속 증가함에 따라 빠르고 안정적인 번역에 대한 요구도 증가합니다. AllChat을 사용하면 언어를 구사하지 않아도 전 세계의 모든 사람과 대화 할 수 있습니다.",
            ru: "По мере того как общение продолжает расти в глобальном масштабе, растет и потребность в быстром и надежном переводе. С AllChat вы можете общаться с кем угодно по всему миру, даже если вы не говорите на его языке.",
            tl: "Tulad ng patuloy na pagtaas ng komunikasyon sa isang global scale, gayon din ang hinihingi para sa mabilis, maaasahang pagsasalin. Sa AllChat, maaari kang makipag-usap sa kahit sino sa buong mundo, kahit na hindi ka nagsasalita ng kanilang wika.",
            te: "ప్రపంచ స్థాయిలో కమ్యూనికేషన్ పెరుగుతూనే ఉన్నందున, శీఘ్ర, నమ్మకమైన అనువాదం కోసం డిమాండ్ కూడా పెరుగుతుంది. AllChat తో, మీరు వారి భాష మాట్లాడకపోయినా ప్రపంచవ్యాప్తంగా ఎవరితోనైనా మాట్లాడవచ్చు.",
            vi: "Khi truyền thông tiếp tục tăng trên phạm vi toàn cầu, thì nhu cầu dịch thuật nhanh chóng, đáng tin cậy cũng vậy. Với AllChat, bạn có thể nói chuyện với bất kỳ ai trên toàn thế giới, ngay cả khi bạn không nói được ngôn ngữ của họ."
        },
        welcome: {
            en: "Welcome to AllChat!",
            es: "¡Bienvenido a AllChat!",
            zh: "欢迎来到AllChat！",
            ar: "مرحبًا بك في AllChat!",
            fr: "Bienvenue sur AllChat!",
            de: "Willkommen bei AllChat!",
            hi: "AllChat में आपका स्वागत है!",
            ja: "AllChatへようこそ！",
            ko: "AllChat에 오신 것을 환영합니다!",
            ru: "Добро пожаловать в AllChat!",
            tl: "Maligayang pagdating sa AllChat!",
            te: "ఆల్ చాట్‌కు స్వాగతం!",
            vi: "Chào mừng đến với AllChat!"
        },
        bring: {
            en: "Bring People Together",
            es: "Juntar a la gente",
            zh: "凝聚人心",
            ar: "جمع الناس معا",
            fr: "Rassembler les gens",
            de: "Leute zusammenbringen",
            hi: "लोगों को एक साथ लाने के लिए",
            ja: "人をつなぐ",
            ko: "사람들을 하나로 모으기",
            ru: "Соберите людей вместе",
            tl: "Magkasama ang mga Tao",
            te: "ప్రజలను కలిసి తీసుకురండి",
            vi: "Đưa mọi người gần lại với nhau"
        },
        start: {
            en: "Start Chatting",
            es: "Comience a chatear",
            zh: "开始聊",
            ar: "ابدأ الدردشة",
            fr: "Commencez à discuter",
            de: "Starten Sie den Chat",
            hi: "चैटिंग शुरू करें",
            ja: "チャットを開始",
            ko: "채팅 시작",
            ru: "Начать чат",
            tl: "Mag-umpisang mag-usap",
            te: "చాటింగ్ ప్రారంభించండి",
            vi: "Bắt đầu trò chuyện"
        },
        rooms: {
            en: "Chatrooms",
            es: "Habitaciones",
            zh: "房间数",
            ar: "غرف",
            fr: "Pièces",
            de: "Räume",
            hi: "कमरा",
            ja: "部屋",
            ko: "대화방",
            ru: "Чаты",
            tl: "Mga silid",
            te: "రూములు",
            vi: "Phòng"
        },
        signout: {
            en: "Sign Out",
            es: "Desconectar",
            zh: "登出",
            ar: "خروج",
            fr: "Déconnexion",
            de: "Ausloggen",
            hi: "प्रस्थान करें",
            ja: "サインアウト",
            ko: "로그 아웃",
            ru: "Выход",
            tl: "Mag-sign Out",
            te: "సైన్ అవుట్ చేయండి",
            vi: "Đăng xuất"
        },
        logged: {
            en: "Logged In",
            es: "Conectado",
            zh: "登录",
            ar: "تم تسجيل الدخول",
            fr: "Connecté",
            de: "Eingeloggt",
            hi: "पमें लॉग इन",
            ja: "ログインしました",
            ko: "로그인",
            ru: "Войти в систему",
            tl: "Nakalog-in",
            te: "లాగిన్ అయ్యారు",
            vi: "Đăng nhập"
        },
        norooms: {
            en: "No Rooms, Create One and Get Started!",
            es: "¡Sin habitaciones, cree una y comience!",
            zh: "没有房间，创建一个并开始！",
            ar: "لا غرف ، أنشئ غرفة وابدأ!",
            fr: "Pas de chambres, créez-en une et commencez!",
            de: "Keine Zimmer, erstellen Sie eines und legen Sie los!",
            hi: "नो रूम, क्रिएट वन एंड गेट स्टार्टेड!",
            ja: "部屋なし、1つ作成して始めましょう！",
            ko: "방 없음, 하나 만들기 및 시작!",
            ru: "Нет комнат, создайте и начните!",
            tl: "Walang mga Kuwarto, Lumikha ng Isa at Magsimula!",
            te: "గదులు లేవు, ఒకదాన్ని సృష్టించండి మరియు ప్రారంభించండి!",
            vi: "Không có phòng, tạo một và bắt đầu!"
        },
        demo: {
            en: "How AllChat Works",
            es: "Cómo funciona AllChat",
            zh: "AllChat如何运作",
            ar: "كيف يعمل AllChat",
            fr: "Comment fonctionne AllChat",
            de: "Wie AllChat funktioniert",
            hi: "ऑलचैट कैसे काम करता है",
            ja: "AllChatの仕組み",
            ko: "AllChat 작동 방식",
            ru: "Как работает AllChat",
            tl: "Paano gumagana ang AllChat",
            te: "ఆల్ చాట్ ఎలా పనిచేస్తుంది",
            vi: "Cách thức hoạt động của AllChat"
        },
        par: {
            en: "When signing up, you can select your preferred language from the dropdown menu. (English will be selected by default if no choice is made).",
            es: "Al registrarse, puede seleccionar su idioma preferido en el menú desplegable. (El inglés se seleccionará de forma predeterminada si no se realiza ninguna elección).",
            zh: "注册时，您可以从下拉菜单中选择首选语言.（如果没有选择，默认情况下将选择英语).",
            ar: "عند الاشتراك ، يمكنك تحديد لغتك المفضلة من القائمة المنسدلة. (سيتم تحديد اللغة الإنجليزية بشكل افتراضي إذا لم يتم تحديد أي خيار).",
            fr: "Lors de votre abonnement, vous pouvez sélectionner votre langue préférée dans le menu déroulant.(L'anglais sera sélectionné par défaut si aucune option n'est sélectionnée).",
            de: "Beim Abonnieren können Sie Ihre bevorzugte Sprache aus dem Dropdown-Menü auswählen.(Englisch wird standardmäßig ausgewählt, wenn keine Option ausgewählt ist).",
            hi: "सदस्यता लेते समय, आप ड्रॉप-डाउन मेनू से अपनी पसंदीदा भाषा का चयन कर सकते हैं।(यदि कोई विकल्प नहीं चुना गया है तो अंग्रेजी को डिफ़ॉल्ट रूप से चुना जाएगा)।",
            ja: "サブスクライブするときに、ドロップダウンメニューから希望の言語を選択できます。オプションが選択されていない場合、英語がデフォルトで選択されます）。",
            ko: "가입 할 때 드롭 다운 메뉴에서 원하는 언어를 선택할 수 있습니다.(옵션을 선택하지 않으면 영어가 기본적으로 선택됩니다).",
            ru: "При подписке вы можете выбрать предпочитаемый язык из выпадающего меню.(Английский будет выбран по умолчанию, если не выбрана ни одна опция).",
            tl: "Kapag nag-subscribe, maaari mong piliin ang iyong ginustong wika mula sa drop-down menu.(Ang Ingles ay mapipili nang default kung walang pagpipilian ay napili).",
            te: "సభ్యత్వం పొందినప్పుడు, మీరు డ్రాప్-డౌన్ మెను నుండి మీకు ఇష్టమైన భాషను ఎంచుకోవచ్చు.(ఎంపికను ఎంచుకోకపోతే ఇంగ్లీష్ అప్రమేయంగా ఎంపిక చేయబడుతుంది).",
            vi: "Khi đăng ký, bạn có thể chọn ngôn ngữ ưa thích từ menu thả xuống.(Tiếng Anh sẽ được chọn theo mặc định nếu không có tùy chọn nào được chọn)."
        },
        par2: {
            en: "Then create a room, or join an existing room, to begin chatting with people all around the world.",
            es: "Luego crea una sala, o únete a una sala existente, para comenzar a chatear con personas de todo el mundo.",
            zh: "然后创建一个会议室，或加入现有会议室，开始与世界各地的人们聊天。",
            ar: "ثم أنشئ غرفة ، أو انضم إلى غرفة موجودة ، لبدء الدردشة مع أشخاص من جميع أنحاء العالم.",
            fr: "Créez ensuite une salle ou rejoignez une salle existante pour commencer à discuter avec des gens du monde entier.",
            de: "Erstellen Sie dann einen Raum oder schließen Sie sich einem vorhandenen Raum an, um mit Menschen auf der ganzen Welt zu chatten.",
            hi: "फिर दुनिया भर के लोगों के साथ बातचीत शुरू करने के लिए, एक कमरा बनाएं, या एक मौजूदा कमरे में शामिल हों।",
            ja: "次に、部屋を作成するか、既存の部屋に参加して、世界中の人々とチャットを始めます。",
            ko: "그런 다음 방을 만들거나 기존 방에 가입하여 전 세계 사람들과 채팅을 시작하십시오.",
            ru: "Затем создайте комнату или присоединитесь к существующей комнате, чтобы начать общаться с людьми со всего мира.",
            tl: "Pagkatapos ay lumikha ng isang silid, o sumali sa isang umiiral na silid, upang simulan ang pakikipag-chat sa mga tao sa buong mundo.",
            te: "ప్రపంచవ్యాప్తంగా ఉన్న వ్యక్తులతో చాట్ చేయడం ప్రారంభించడానికి ఒక గదిని సృష్టించండి లేదా ఇప్పటికే ఉన్న గదిలో చేరండి.",
            vi: "Sau đó, tạo một phòng, hoặc tham gia một phòng hiện có, để bắt đầu trò chuyện với mọi người trên khắp thế giới."
        },
        tran: {
            en: "With AllChat, the Language Barrier is Broken!",
            es: "¡Con AllChat, la barrera del idioma está rota!",
            zh: "有了AllChat，语言障碍就被打破了！",
            ar: "مع AllChat ، يتم كسر حاجز اللغة!",
            fr: "Avec AllChat, la barrière de la langue est brisée!",
            de: "Mit AllChat ist die Sprachbarriere gebrochen!",
            hi: "ऑलचैट के साथ, भाषा बैरियर टूटी हुई है!",
            ja: "AllChatを使用すると、言語の壁が壊れます！",
            ko: "AllChat으로 언어 장벽이 깨졌습니다!",
            ru: "С AllChat языковой барьер сломан!",
            tl: "PaSa AllChat, Broken ang Wika ng Wika!",
            te: "ఆల్చాట్‌తో, భాషా అవరోధం విరిగింది!",
            vi: "Với AllChat, Rào cản ngôn ngữ bị hỏng!"
        },
        tranpar: {
            en: 'Click on "See Translation" to view a message translated in your preferred language,and if you want to see the original, click "See Original".',
            es: 'Haga clic en "Ver traducción" para ver un mensaje traducido en su idioma preferido,y si desea ver el original, haga clic en "Ver original".',
            zh: '点击“查看翻译”以查看您首选语言翻译的邮件，如果您想查看原图，请单击“查看原图”。',
            ar: 'انقر على "انظر الترجمة" لعرض رسالة مترجمة إلى لغتك المفضلة ، وإذا كنت تريد مشاهدة الأصل ، فانقر فوق "انظر الأصلي".',
            fr: `Cliquez sur "Voir la traduction" pour afficher un message traduit dans votre langue préférée,et si vous voulez voir l'original, cliquez sur "Voir l'original".`,
            de: 'Klicken Sie auf "Übersetzung anzeigen", um eine in Ihre bevorzugte Sprache übersetzte Nachricht anzuzeigen. und wenn Sie das Original sehen möchten, klicken Sie auf "Original anzeigen".',
            hi: 'अपनी पसंदीदा भाषा में अनुवादित संदेश देखने के लिए "अनुवाद देखें" पर क्लिक करें, और यदि आप मूल देखना चाहते हैं, तो "मूल देखें" पर क्लिक करें।',
            ja: '「翻訳を表示」をクリックして、希望の言語に翻訳されたメッセージを表示します。オリジナルを見たい場合は、「オリジナルを見る」をクリックしてください。',
            ko: '원하는 언어로 번역 된 메시지를 보려면 "번역보기"를 클릭하십시오. 원본을 보려면 "원본보기"를 클릭하십시오.',
            ru: 'Нажмите «Просмотреть перевод», чтобы просмотреть сообщение, переведенное на выбранный вами язык, и если вы хотите увидеть оригинал, нажмите «Посмотреть оригинал».',
            tl: 'Mag-click sa "Tingnan ang Pagsasalin" upang makita ang isang mensahe na isinalin sa iyong ginustong wika, at kung nais mong makita ang orihinal, i-click ang "Tingnan ang Orihinal".',
            te: 'మీకు ఇష్టమైన భాషలో అనువదించబడిన సందేశాన్ని చూడటానికి "అనువాదం చూడండి" పై క్లిక్ చేయండి, మరియు మీరు అసలైనదాన్ని చూడాలనుకుంటే, "అసలు చూడండి" క్లిక్ చేయండి.',
            vi: 'Nhấp vào "Xem bản dịch" để xem tin nhắn được dịch bằng ngôn ngữ ưa thích của bạn, và nếu bạn muốn xem bản gốc, nhấp vào "Xem bản gốc".'
        },
        power: {
            en: "Powered By:",
            es: "Construido con:",
            zh: "内置：",
            ar: "بنيت مع:",
            fr: "Construit avec:",
            de: "Gebaut mit:",
            hi: "इसके साथ निर्मित:",
            ja: "で構築：",
            ko: "내장 :",
            ru: "Построен с:",
            tl: "Itinayo Gamit ang:",
            te: "దీనితో నిర్మించబడింది:",
            vi: "Được xây dựng với:"
        },
        contact: {
            en: "Contact:",
            es: "Contacto:",
            zh: "联系：",
            ar: "اتصل:",
            fr: "Contact:",
            de: "Kontakt:",
            hi: "संपर्क करें:",
            ja: "連絡先：",
            ko: "접촉:",
            ru: "Контактное лицо:",
            tl: "Makipag-ugnay sa:",
            te: "సంప్రదించండి:",
            vi: "Tiếp xúc:"
        },
        feedback: {
            en: "Send Feedback:",
            es: "Enviar comentarios:",
            zh: "发送反馈：",
            ar: "ارسل رأيك:",
            fr: "Envoyer des commentaires:",
            de: "Feedback schicken:",
            hi: "प्रतिक्रिया भेजें:",
            ja: "フィードバックを送信：",
            ko: "의견 보내기 :",
            ru: "Отправить отзыв:",
            tl: "Magbigay ng feedback:",
            te: "అభిప్రాయాన్ని పంపండి:",
            vi: "Gửi thông tin phản hồi:"
        },
        developers: {
            en: "Developers:",
            es: "Creadores:",
            zh: "创建者：",
            ar: "المؤلفون:",
            fr: "Créateurs:",
            de: "Schöpfer:",
            hi: "रचनाकारों:",
            ja: "クリエイター：",
            ko: "제작자 :",
            ru: "Творцы:",
            tl: "Mga Lumikha:",
            te: "క్రియేటర్స్:",
            vi: "Người tạo"
        },
    }