export const NEW_MESSAGE = "NEW_MESSAGE";
export const WELCOME_MESSAGE = "WELCOME_MESSAGE";
export const USERJOIN_MESSAGE = "USERJOIN_MESSAGE";
export const NEW_ROOM = "NEW_ROOM";
export const DELETE_ROOM_BY_ID = "DELETE_ROOM_BY_ID";
